### ISSUE TITLE
Optional argument suggestions

### ISSUE THREAD

**Issue by pettomartino** [starlingbank/starling-developer-sdk#17]
Hello guys,

First of all, thanks for this SDK, it's really handy.

I'd like to make a suggestion for those `Starling` methods signature, IMHO, it's a bit strange to have the first argument optional. Let's get as example the `getTransaction` method:

```
getTransaction (accessToken = this.config.accessToken, transactionId, source)
```

If I want to use this method as I suppose most of the use cases are going to be by using the `accessToken` from the construtor I must use like this:

`starlingInstance.getTransaction(undefined, '12334-123123-12313-123123')`

Although It's a bit Java way, I'd rather a `setAccessToken()` method and then ditch the `accessToken` argument from all methods signature(inside Starling class of course), using it straight from `this.config.accessToken`

Another suggestion, which I more Javascriptish is using a single object as argument, since there's that `typeValidation` function what helps validate the methods arguments that wouldn't be that tricky.

**Comment by domdomegg** [comment]
Thanks for your suggestions! I know it's been a long time since you initially proposed this but I'd like to let you know that v1.0.0 of the SDK now follows the singular object argument pattern :)
