### ISSUE TITLE
OAuth URL correct?

### ISSUE THREAD

**Issue by rossmeyerza** [starlingbank/starling-developer-sdk#18]
Firstly, thanks for the sdk.

Feel like I'm going nuts; The getOAuthToken method in the OAuth class references:
https://github.com/starlingbank/starling-developer-sdk/blob/0775852fe41602015da5d136f2c26845247fb1aa/src/entities/oauth.js#L70

Which is getting the domain from the constructor defaults:
https://github.com/starlingbank/starling-developer-sdk/blob/0775852fe41602015da5d136f2c26845247fb1aa/src/starling.js#L25

However the developer docs say:
"To exchange the authorisation code, `POST` as `application/x-www-form-urlencoded` from parameters, to `https://api.starlingbank.com/oauth/access-token`"

Either way though I am struggling to authenticate, getting "authorization_code could not be verified, it could be invalid, expired or revoked" from the sandbox :/

**Comment by domdomegg** [comment]
Hi Ross, thanks for flagging this and sorry for the insane delay in replying to this. You're right, it should be `POST`ed to the main API, not the oauth subdomains. I've raised #35 to sort this out.
