### ISSUE TITLE
:bug: in web SDK the get OAuthToken uses GET instead of POST method

### ISSUE THREAD

**Issue by DannyRussellWP** [starlingbank/starling-developer-sdk#8]
in OAuth.js file the GetOAuthToken method uses a GET method instead of a POST (as per the instructions (https://jsapi.apiary.io/apis/starlingbankapi/introduction/authentication/5.-exchange-for-an-access-token.html). This is causing both the get original token and refresh token methods to return an error HTML page rather than the required response.

I have tested this using postman (using GET and POST) to verify that this is the issue and that the request should be a POST

**Comment by Stephan5** [comment]
Well that is embarrassing. 
Thanks for raising this...

**Comment by Stephan5** [comment]
@DannyRussellWP I will release to npm this afternoon 👍

**Comment by DannyRussellWP** [comment]
No problems @Stephan5 it happens to all of us. Let me know when you release and I will update my code

**Comment by Stephan5** [comment]
@DannyRussellWP  Just updated to v0.1.6 on npm. Should be available now.
Do join the [developer slack](https://developer.starlingbank.com/community) channel if you have any questions or find any other glaring oversights.
